# Generated by Django 3.0.8 on 2020-07-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200716_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
